apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: nomnom-system
type: Opaque
stringData:
  # User service environment variables (for Spring Boot with MongoDB Atlas)
  SPRING_DATA_MONGODB_URI: "mongodb+srv://username:password@your-atlas-cluster.mongodb.net/user-service?retryWrites=true&w=majority"
  SPRING_DATA_MONGODB_DATABASE: "user-service"
  SERVER_PORT: "8085"
  # Add other required environment variables for user service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nomnom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: dasunwickr/user-service:latest
        ports:
        - containerPort: 8085
        envFrom:
        - secretRef:
            name: user-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: nomnom-system
spec:
  selector:
    app: user-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP