apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: nomnom-system
type: Opaque
stringData:
  # Order service environment variables (for Spring Boot with MongoDB Atlas)
  SPRING_DATA_MONGODB_URI: "mongodb+srv://username:password@your-atlas-cluster.mongodb.net/order-service?retryWrites=true&w=majority"
  SPRING_DATA_MONGODB_DATABASE: "order-service"
  SERVER_PORT: "8081"
  # Add other required environment variables for order service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: nomnom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: dasunwickr/order-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: order-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: nomnom-system
spec:
  selector:
    app: order-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP